#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
#MISE description="Run linters"
set -euo pipefail

UNFORMATTED=$(gofmt -l .)
if [ -n "$UNFORMATTED" ]; then
  echo "Unformatted files:"
  echo "$UNFORMATTED"
  exit 1
fi

go vet ./...
