#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
#MISE description="Run tests with coverage"
set -euo pipefail

BUILD_DIR=build
mkdir -p "$BUILD_DIR"

go test -v -race -coverprofile="$BUILD_DIR/coverage.out" ./...
